### ISSUE TITLE
Error after Update to Home Assistant 2021.12.0b0  /  Home Assistant OS 7.0

### ISSUE THREAD

**Issue by salopette** [AlexxIT/WebRTC#175]
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 10:36:56 (1 occurrences)
Last logged: 10:36:56

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by miit86** [comment]
Same Problem Here

**Comment by jscherry** [comment]
Same problem. Posted logs under another issue with no response to either? This has been a game changer for me, awesome integration. I hope this can be fixed?

**Comment by Mincka** [comment]
I proposed a PR to fix this. In the meantime, you can manually edit your `config/custom_components/webrtc/utils.py` like this
https://github.com/AlexxIT/WebRTC/pull/177/files#diff-268266fb86d71bd71ed88a54850bd9ff45a46f014acb42741ed28173a817cb8eR74

**Comment by AlexxIT** [comment]
Duplicate #156
