### ISSUE TITLE
Does not start any more with core-2021.12.0b0

### ISSUE THREAD

**Issue by eikowagenknecht** [AlexxIT/WebRTC#178]
Using 2.1.1 after Upgrading to core-2021.12.0b0 I get an error message on startup and the integration doesn't work (no video shown):

```
2021-12-05 14:09:33 ERROR (MainThread) [homeassistant.setup] Error during setup of component webrtc
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
result = await task
File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
utils.register_static_path(hass.http.app, url_path, path)
File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
app['allow_cors'](route)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
return self._state[key]
KeyError: 'allow_cors'
```

**Comment by MrKittenK** [comment]
Can confirm this happens to me also after the latest update

**Comment by AlexxIT** [comment]
Duplicate #156
