### ISSUE TITLE
BREAKING CHANGE in HA 2021.12

### ISSUE THREAD

**Issue by bafplus** [AlexxIT/WebRTC#179]
Although HA is giving suggestions for months WebRTC is still not updated to stay working with Home Assistant. From HA 2021.12 this will be a BREAKING CHANGE:

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by zvldz** [comment]
update to master

**Comment by bafplus** [comment]
I use the HACS version, shouldnt that be on master already?

Op ma 6 dec. 2021 om 17:15 schreef zvldz ***@***.***>:

**Comment by zvldz** [comment]
Changes in the master version of the component, no release yet. You can install the master version via hacs

**Comment by bafplus** [comment]
You cant, HACS says: 

Repository 'alexxit/webrtc' exists in the store.

**Comment by sean-m-sullivan** [comment]
Took me a moment in hacs when adding repository 
![image](https://user-images.githubusercontent.com/30054029/144953171-7417c656-17a9-4d0b-b9e6-e692310c4c23.png)

**Comment by sean-m-sullivan** [comment]
however I just switched to master and have the same issue with allow_cors

**Comment by AlexxIT** [comment]
Duplicate

**Comment by bafplus** [comment]
Switching to Master did fix it, but i would suggest to push a new version else everyones HA install will fail on WebRTC next saturday.

**Comment by AlexxIT** [comment]
@bafplus if you see this error, you have not installed the master version

**Comment by gryphon-wg** [comment]
2AlexxIT
Installed master version, 2 time reboot, but  still no luck

**HACS**: " version downloaded 0e45d1"
**LOGS**: Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
**Integrations**: Not loaded

**Comment by AlexxIT** [comment]
@gryphon-wg as you can see, line 74 don't have this code. So you haven't installed the master version

https://github.com/AlexxIT/WebRTC/blob/0e4d5d1f2b5a49d45b8ea3af70084499913585c0/custom_components/webrtc/utils.py#L74

**Comment by AlexxIT** [comment]
#156
