### ISSUE TITLE
Fails to load in HA 2021.12

### ISSUE THREAD

**Issue by cdn4lf** [AlexxIT/WebRTC#185]
Fails to start after upgrade to 2021.12.0

```This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 3:39:47 PM (1 occurrences)
Last logged: 3:39:47 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
```

**Comment by Arquiteto** [comment]
Check issue #182 for a solution.

**Comment by cdn4lf** [comment]
Thanks. Switching to master branch resolved the issue

**Comment by AlexxIT** [comment]
#156
