### ISSUE TITLE
Home Assistant Core 2021.12 error: tintegrations and platforms could not be set up:

### ISSUE THREAD

**Issue by Yamaha0014** [AlexxIT/WebRTC#186]
Hi After upgrade to Home Assistant Core 2021.12 integration is not working:

`Ten błąd pochodzi z niestandardowej integracji.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 21:34:29 (1 occurrences)
Last logged: 21:34:29

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
`

**Comment by Arquiteto** [comment]
Check issue #182 for a solution.

**Comment by Yamaha0014** [comment]
> Check issue #182 for a solution.

ok working Thx

**Comment by AlexxIT** [comment]
#156
