### ISSUE TITLE
Integration NOT LOADED after updating home assistant to 2021.12

### ISSUE THREAD

**Issue by aljubori** [AlexxIT/WebRTC#187]
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 10:59:09 PM (1 occurrences)
Last logged: 10:59:09 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by serlinGi** [comment]
hi, read the instructions at link:
https://github.com/AlexxIT/WebRTC/pull/177/files#diff-268266fb86d71bd71ed88a54850bd9ff45a46f014acb42741ed28173a817cb8eR74 , recalled in issue #182.
I also solved.
thanks to alex

**Comment by LordNex** [comment]
how do you resolve this? has the repo just not updated on my side or has the fix not been pushed

**Comment by AlexxIT** [comment]
#156
