### ISSUE TITLE
WebRTC not working after anymore after upgrade to HA 2021.12.0

### ISSUE THREAD

**Issue by mkleijn** [AlexxIT/WebRTC#188]
Hi, 

After upgrading HA to latest version (2021.12.0) I get this error in the logs:

2021-12-12 08:00:52 ERROR (MainThread) [homeassistant.setup] Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by proinc-bayles** [comment]
#182

**Comment by LordNex** [comment]
Getting the same errors

`This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 1:17:47 AM (1 occurrences)
Last logged: 1:17:47 AM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
`

**Comment by LordNex** [comment]
I tried redownloading from HACS with no success. tried to manually download and replace utils.py and restart and that failed completely.

**Comment by jonasschwenk** [comment]
Same here. After update to ha Cor 2021.12.0 webrtc isn't working anymore

**Comment by AlexxIT** [comment]
#156
