### ISSUE TITLE
Integration not loading after HA container update

### ISSUE THREAD

**Issue by dandanarsk** [AlexxIT/WebRTC#189]
Ha container updated last night, webrtc wo t load the integration. Tries to reinstall, same error. 
![Screenshot_20211212-081458_Home Assistant](https://user-images.githubusercontent.com/44378857/145705414-dc9eb669-9caa-4e91-add6-fe20ac30d3e4.png)

**Comment by kloodhu** [comment]
sam e here

**Comment by saneone** [comment]
+1 

WebRTC doesn't work after updating to 2021.12

**Comment by wonderiuy** [comment]
The same here:

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 10:03:01 (1 occurrences)
Last logged: 10:03:01

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by besiktas97** [comment]
I've got the same issue. Waiting for a fix over here.

**Comment by AlexxIT** [comment]
#156
