### ISSUE TITLE
Can't start addon on HA 2021.12.0

### ISSUE THREAD

**Issue by eugene-ki** [AlexxIT/WebRTC#191]
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 12:48:19 (1 occurrences)
Last logged: 12:48:19

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by Tyrian81** [comment]
same issue

**Comment by catatonico2** [comment]
Same here.

**Comment by fritanga** [comment]
same issue here

**Comment by besiktas97** [comment]
Same over here

**Comment by Langybangy** [comment]
Same error here too:
![image](https://user-images.githubusercontent.com/16418593/145708915-0c119fdc-f361-4026-ac65-aa580bf174ac.png)

**Comment by VolkerLaude** [comment]
Same here

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 10:49:03 (1 occurrences)
Last logged: 10:49:03

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by tenallero** [comment]
Same here

**Comment by AlexxIT** [comment]
#156
