### ISSUE TITLE
ERROR (MainThread) [homeassistant.setup] Error during setup of component webrtc - HA 2021.12.0

### ISSUE THREAD

**Issue by oigan** [AlexxIT/WebRTC#192]
Hi, I got this error with the last update of HA 2021.12.0

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 13:20:17 (1 occurrences)
Last logged: 13:20:17

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by fabiobrolo** [comment]
I´m facing the same issue after the upgrade.

**Comment by AlexxIT** [comment]
#156
