### ISSUE TITLE
Integration breaks with Home Assistant 21.12.0

### ISSUE THREAD

**Issue by r3tr0sp3c** [AlexxIT/WebRTC#194]
Integration breaks once you upgrade to Home Assistant 21.12.0

```
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 18:55:01 (1 occurrences)
Last logged: 18:55:01

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
```

**Comment by AlexxIT** [comment]
#156
