### ISSUE TITLE
Error during setup of component webrtc after home assitant 2021.12.0 update.

### ISSUE THREAD

**Issue by jmlc11** [AlexxIT/WebRTC#197]
This is the error in home assistant logs:
Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by aaamoeder** [comment]
same for me.. 2021.12 broke it..

**Comment by liquidbear99** [comment]
Same for me

**Comment by mikedrawback** [comment]
same here

**Comment by nkm8** [comment]
There is already a fix for this error on the master branch that hasn't been released yet. I upgraded and everything is working normally.

**Comment by AlexxIT** [comment]
#156
