### ISSUE TITLE
Intergration error on boot since 2021.12.0

### ISSUE THREAD

**Issue by SebastiaanRutgers** [AlexxIT/WebRTC#198]
Intergration does not load since upgrading to 2021.12.0. Same error on 2021.12.1.

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by AlexxIT** [comment]
#156
