### ISSUE TITLE
KeyError: 'allow_cors' in latest HASSIO Installation Version 2021.12.1 

### ISSUE THREAD

**Issue by galex80** [AlexxIT/WebRTC#200]
Since the last update from Home Assistant to Version 2021.12.0 (1) the addon WebRTC is not working anymore and runs into an issue, see log:
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 2:30:31 PM (1 occurrences)
Last logged: 2:30:31 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by galex80** [comment]
Duplicate of https://github.com/AlexxIT/WebRTC/issues/156
