### ISSUE TITLE
Broken siince HA upgrade to 2021.12.1

### ISSUE THREAD

**Issue by Gitspecial** [AlexxIT/WebRTC#204]
Even Bunny test stream doesn't work anymore since the last HA update. What is the fix?

**Comment by martijnrenkema** [comment]
I have the same problem. is there a fix?

**Comment by gomble** [comment]
Same problem

**Comment by Zagor4** [comment]
This is the Error Log: 

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by AlexxIT** [comment]
#156
