### ISSUE TITLE
HA 2021.12.1 Supervisor. Mistake - KeyError: 'url'

### ISSUE THREAD

**Issue by aeros2** [AlexxIT/WebRTC#207]
Please help!
Version WebRtc 2.2.0

Installation via HACS with an error -

`Success!
WebRTC Camera configuration record created
Integration failed to load, please try restarting Home Assistant.`

Error in the log file -

```
Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:93
Integration: WebRTC Camera (documentation, issues)
First occurred: 15:50:06 (1 occurrences)
Last logged: 15:50:06

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 82, in async_setup
    await utils.init_resource(hass, url_path, str(version))
  File "/config/custom_components/webrtc/utils.py", line 93, in init_resource
    if not item['url'].startswith(url):
KeyError: 'url'
```

**Comment by silver0007** [comment]
Got the same in 2021.12.1 and rolled back to 2021.11.5 where everything works.
Looks like integration is not working with newest core release (yet), so looking forward for a fix.

**Comment by pnt-thiago** [comment]
I experiencing the following error with core-2021.12.2:

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: webrtc (documentation, issues)
First occurred: 9:32:26 AM (1 occurrences)
Last logged: 9:32:26 AM

```
Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 229, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'
```

**Comment by AlexxIT** [comment]
Should be fixed in v3
