### ISSUE TITLE
OSError: [Errno 8] Exec format error: '/home/homeassistant/homeassistant/rtsp2webrtc_v5_freebsd'

### ISSUE THREAD

**Issue by ckbisek** [AlexxIT/WebRTC#225]
Receiving error with WebRTC
Home Assistant 2021.12.3
WebRTC v2.2.0

Logger: root
Source: custom_components/webrtc/utils.py:175
Integration: WebRTC Camera (documentation, issues)
First occurred: 10:35:08 AM (1 occurrences)
Last logged: 10:35:08 AM

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/home/homeassistant/homeassistant/custom_components/webrtc/utils.py", line 175, in run
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/homeassistant/homeassistant/rtsp2webrtc_v5_freebsd'

**Comment by ckbisek** [comment]
I've performed a rollback to:
Home Assistant 2021.11.5
WebRTC v2.1.1

Regained full functionality, will remain at these levels for the time being

**Comment by ckbisek** [comment]
@AlexxIT 

FWIW
I have moved to the HASS Linux image and abandoned my over-engineered FreeBSD instance.  Running latest versions and working perfectly --amongst many other integrations and having access to addons.  

Wish I did it sooner...
