### ISSUE TITLE
Runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by sachinss123** [AlexxIT/WebRTC#234]
Hi there, I was a happy user of webrtc for showing my doorbell camera on my wall mounted tablet, but in the last few weeks it has suddenly stopped working. Here are my system details:

```
webrtc - master (installed from HACS, also deleted, removed the custom_components folder and re-installed)
Installation Type | Home Assistant OS
Version | core-2021.12.1
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.7
Operating System Family | Linux
Operating System Version | 5.10.17-v8
CPU Architecture | aarch64
```

This is my lovelace card:

```
type: custom:webrtc-camera
url: rtsp://admin:password@192.168.0.69:554/cam/realmonitor?channel=1&subtype=1

```

And this is what I see in the debug logs:

```
2022-01-07 10:16:56 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:16:56 Server Start Awaiting Signal
2022-01-07 10:16:58 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:16:58 Stream Try Connect rtsp://admin:password@192.168.0.69:554/cam/realmonitor?channel=1&subtype=1
2022-01-07 10:16:58 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: slice bounds out of range [:-1]
2022-01-07 10:16:58 DEBUG (webrtc) [custom_components.webrtc.utils] 
2022-01-07 10:16:59 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 38 [running]:
2022-01-07 10:16:59 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:16:59 Server Start Awaiting Signal
2022-01-07 10:17:08 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:08 Stream Try Connect rtsp://admin:password@192.168.0.69:554/cam/realmonitor?channel=1&subtype=1
2022-01-07 10:17:08 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: slice bounds out of range [:-1]
2022-01-07 10:17:09 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:08 Server Start Awaiting Signal
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:23 Stream Try Connect rtsp://admin:password@192.168.0.69:554/cam/realmonitor?channel=1&subtype=1
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: slice bounds out of range [:-1]
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] 
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 40 [running]:
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).GetInit(0x40000a2370, 0x400009fd50, 0x0, 0x0, 0x0, 0x0, 0x400012b528, 0x3, 0x0)
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] 	C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:278 +0x814
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x400016e7e0, 0x4000200190, 0x4b)
2022-01-07 10:17:23 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:23 Server Start Awaiting Signal
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:38 Stream Try Connect rtsp://admin:password@192.168.0.69:554/cam/realmonitor?channel=1&subtype=1
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: slice bounds out of range [:-1]
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] 
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 7 [running]:
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).GetInit(0x4000318320, 0x400009bd50, 0x0, 0x0, 0x0, 0x0, 0x60, 0x4000300480, 0x4000042800)
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] 	C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:278 +0x814
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40003c8090, 0x40000260a0, 0x4b)
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] 	q:/Development/Go/RTSPtoWebRTC/http.go:269 +0x33c
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] 	q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-01-07 10:17:38 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:38 Server Start Awaiting Signal
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:53 Stream Try Connect rtsp://admin:password@192.168.0.69:554/cam/realmonitor?channel=1&subtype=1
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: slice bounds out of range [:-1]
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] 
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 36 [running]:
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).GetInit(0x4000068320, 0x4000098d50, 0x0, 0x0, 0x0, 0x0, 0x400003cd28, 0x3, 0x0)
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] 	C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:278 +0x814
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40003c4090, 0x40000260a0, 0x4b)
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] 	q:/Development/Go/RTSPtoWebRTC/http.go:269 +0x33c
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] 	q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-01-07 10:17:53 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/01/07 10:17:53 Server Start Awaiting Signal

```

Any help would be appreciated. I've also tested the stream in VLC and it works perfectly.

S.

**Comment by sawenz** [comment]
I face the same issue!
`2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 35 [running]:
2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).GetInit(0x4000100190, 0x4000161d50, 0x0, 0x0, 0x0, 0x0, 0x400003adb8, 0x1c6e8, 0x40000993e0)
2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:278 +0x814
2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40000f8ea0, 0x40002b71cc, 0x27)
2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:269 +0x33c
2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-04-10 09:48:55 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/10 09:48:55 Server Start Awaiting Signal
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/10 09:49:00 Stream Try Connect rtsp://192.168.178.101:554/mjpeg_stream
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: slice bounds out of range [:-1]
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 54 [running]:
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).GetInit(0x40003422d0, 0x40002ddd50, 0x0, 0x0, 0x0, 0x0, 0x4000380d28, 0x3, 0x0)
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:278 +0x814
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40003301b0, 0x400032e04c, 0x27)
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:269 +0x33c
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-04-10 09:49:00 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/10 09:49:00 Server Start Awaiting Signal`

**Comment by ezanolin** [comment]
WebRTC was working great for the last year with my Ubiquiti UniFi cameras, but after an update it has stopped working. I seem to have the same issues in the debug log. Same as the other people, the streams opens fine in VLC and streams used to work fine before an update.

```
2022-06-06 01:30:19 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration webrtc which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-06-06 01:30:41 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:30:41 Server Start Awaiting Signal
2022-06-06 01:30:53 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:30:53 Stream Try Connect rtsp://192.168.168.100:7447/SoDKQvNlCpbzgyrj
2022-06-06 01:30:53 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:30:53 Stream Try Connect rtsp://192.168.168.100:7447/f8jegDUYzpRZ9cCi
2022-06-06 01:30:53 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:30:53 Set ICEServers [stun:stun.l.google.com:19302]
2022-06-06 01:30:53 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:30:53 WebRTC Ignore Audio Track codec not supported WebRTC support only PCM_ALAW or PCM_MULAW
2022-06-06 01:30:53 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:30:53 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:30:53 Server Start Awaiting Signal
2022-06-06 01:31:05 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:05 Stream Try Connect rtsp://192.168.168.100:7447/f8jegDUYzpRZ9cCi
2022-06-06 01:31:05 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:05 Stream Try Connect rtsp://192.168.168.100:7447/SoDKQvNlCpbzgyrj
2022-06-06 01:31:05 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:31:05 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:05 Server Start Awaiting Signal
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:20 Stream Try Connect rtsp://192.168.168.100:7447/SoDKQvNlCpbzgyrj
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:20 Stream Try Connect rtsp://192.168.168.100:7447/f8jegDUYzpRZ9cCi
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 39 [running]:
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).WritePacket(0x40000a63c0, 0x201, 0xf4240, 0x23139e49fdc0, 0x1312d00, 0x40005dc000, 0x36445, 0x38000, 0x400, 0x76504, ...)
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:287 +0x318
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x4000168900, 0x40001f819c, 0x2c)
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:305 +0x668
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-06-06 01:31:20 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:20 Server Start Awaiting Signal
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:35 Stream Try Connect rtsp://192.168.168.100:7447/SoDKQvNlCpbzgyrj
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:35 Stream Try Connect rtsp://192.168.168.100:7447/f8jegDUYzpRZ9cCi
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 41 [running]:
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).WritePacket(0x40000aa550, 0x201, 0xf4240, 0x23171c5bd3c0, 0x1312d00, 0x40005a8000, 0x36e08, 0x38000, 0x400, 0x76504, ...)
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:287 +0x318
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x4000168870, 0x40001f819c, 0x2c)
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:305 +0x668
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-06-06 01:31:35 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:35 Server Start Awaiting Signal
2022-06-06 01:31:45 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:45 Stream Try Connect rtsp://192.168.168.100:7447/SoDKQvNlCpbzgyrj
2022-06-06 01:31:45 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:45 Stream Try Connect rtsp://192.168.168.100:7447/f8jegDUYzpRZ9cCi
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 10 [running]:
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).WritePacket(0x40004460a0, 0x201, 0xf4240, 0x231998295480, 0x1312d00, 0x4000668000, 0x36b85, 0x38000, 0x400, 0x76504, ...)
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:287 +0x318
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40004321b0, 0x400043000c, 0x2c)
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:305 +0x668
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-06-06 01:31:46 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:31:46 Server Start Awaiting Signal
2022-06-06 01:32:00 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:32:00 Stream Try Connect rtsp://192.168.168.100:7447/SoDKQvNlCpbzgyrj
2022-06-06 01:32:00 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:32:00 Stream Try Connect rtsp://192.168.168.100:7447/f8jegDUYzpRZ9cCi
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 7 [running]:
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).WritePacket(0x4000390230, 0x201, 0xf4240, 0x231d163b2a80, 0x1312d00, 0x4000558000, 0x366aa, 0x38000, 0x400, 0x0, ...)
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:287 +0x318
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40001ef170, 0x400027e37c, 0x2c)
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:305 +0x668
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-06-06 01:32:01 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:32:01 Server Start Awaiting Signal
2022-06-06 01:32:15 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:32:15 Stream Try Connect rtsp://192.168.168.100:7447/SoDKQvNlCpbzgyrj
2022-06-06 01:32:15 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:32:15 Stream Try Connect rtsp://192.168.168.100:7447/f8jegDUYzpRZ9cCi
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 50 [running]:
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).WritePacket(0x40003ac0a0, 0x201, 0xf4240, 0x2320958d6fc0, 0x1312d00, 0x40005e6000, 0x34848, 0x36000, 0x400, 0x76504, ...)
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:287 +0x318
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40000ec7e0, 0x40000d014c, 0x2c)
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:305 +0x668
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: index out of range [2] with length 2
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 25 [running]:
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).WritePacket(0x4000322190, 0x201, 0xf4240, 0x2320958d6fc0, 0x1312d00, 0x40005e6000, 0x34848, 0x36000, 0x400, 0x76504, ...)
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:287 +0x318
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40000ecab0, 0x40000d01ec, 0x2c)
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:305 +0x668
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:237 +0x398
2022-06-06 01:32:16 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/06/06 01:32:16 Server Start Awaiting Signal
```

**Comment by AlexxIT** [comment]
@ezanolin check #305

**Comment by AlexxIT** [comment]
Check my new project. Maybe it handle this situation
https://github.com/AlexxIT/go2rtc

**Comment by AlexxIT** [comment]
Should be fixed in v3
