### ISSUE TITLE
Don't able to connect a cam from VM

### ISSUE THREAD

**Issue by TobiasKarge** [AlexxIT/WebRTC#264]
I installed this Integration on Home Assistant that runs as VM on Synology NAS.
The Integration can't connect an local Stream.

Logger: aiohttp.server
Source: components/rtsp_to_webrtc/config_flow.py:65 
First occurred: 08:27:30 (1 occurrences) 
Last logged: 08:27:30

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 164, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 111, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/components/rtsp_to_webrtc/config_flow.py", line 48, in async_step_user
    if error_code := await self._test_connection(url):
  File "/usr/src/homeassistant/homeassistant/components/rtsp_to_webrtc/config_flow.py", line 65, in _test_connection
    await client.heartbeat()
  File "/usr/local/lib/python3.9/site-packages/rtsp_to_webrtc/webrtc_client.py", line 67, in heartbeat
    await self._request("get", HEARTBEAT_PATH, label="heartbeat")
  File "/usr/local/lib/python3.9/site-packages/rtsp_to_webrtc/webrtc_client.py", line 82, in _request
    resp = await self._session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1146, in _create_direct_connection
    assert port is not None
AssertionError

Logger: homeassistant.components.rtsp_to_webrtc.config_flow
Source: components/rtsp_to_webrtc/config_flow.py:70 
Integration: RTSPtoWebRTC (documentation, issues) 
First occurred: 08:21:51 (6 occurrences) 
Last logged: 08:29:14

RTSPtoWebRTC communication failure: RTSPtoWebRTC server communication failure: 400, message='Expected HTTP/', url=URL('rtsp://192.168.2.156:554/static')
RTSPtoWebRTC communication failure: RTSPtoWebRTC server communication failure: 400, message='Expected HTTP/', url=URL('rtsp://192.168.2.131:554/static')
RTSPtoWebRTC communication failure: RTSPtoWebRTC server communication failure: Cannot connect to host 192.168.1.123:554 ssl:default [Connect call failed ('192.168.1.123', 554)]

## System Health

version | core-2022.2.9
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.9.7
os_name | Linux
os_version | 5.10.98
arch | x86_64
timezone | Europe/Berlin

<details><summary>Home Assistant Cloud</summary>

logged_in | true
-- | --
subscription_expiration | 17. März 2022, 01:00
relayer_connected | true
remote_enabled | true
remote_connected | true
alexa_enabled | true
google_enabled | true
remote_server | eu-central-1-0.ui.nabu.casa
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 7.4
-- | --
update_channel | stable
supervisor_version | supervisor-2022.01.1
docker_version | 20.10.9
disk_total | 30.8 GB
disk_used | 9.6 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Samba share (9.5.1), File editor (5.3.3), Home Assistant Google Drive Backup (0.105.2), Mosquitto broker (6.0.1), Terminal & SSH (9.3.0), SQLite Web (3.2.1)

</details>

<details><summary>Lovelace</summary>

dashboards | 2
-- | --
resources | 7
views | 8
mode | storage

</details>

**Comment by releares** [comment]
Same issue on my Synology VM. I will post my logs and config later and update my post.

**Comment by AlexxIT** [comment]
This is not mine component. You need write to Home Assistant repo
