### ISSUE TITLE
Loading 

### ISSUE THREAD

**Issue by soundiesam** [AlexxIT/WebRTC#271]
Hi 

I am getting this error 

<img width="543" alt="Screenshot 2022-03-09 at 11 50 09" src="https://user-images.githubusercontent.com/20504413/157436513-c8ab4949-7fa5-403e-81ce-b99baa6f6b4a.png">

I have repeatedly restarted Home assistant though

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera ([documentation](https://github.com/AlexxIT/WebRTC), [issues](https://github.com/AlexxIT/WebRTC/issues))
First occurred: 11:48:26 AM (1 occurrences)
Last logged: 11:48:26 AM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

**Comment by AlexxIT** [comment]
#270
