### ISSUE TITLE
Cannot load WebRTC on latest version of HA OS

### ISSUE THREAD

**Issue by NeillHerbst** [AlexxIT/WebRTC#272]
I'm getting the following error:

This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/webrtc/utils.py:74
Integration: WebRTC Camera (documentation, issues)
First occurred: 6:51:08 PM (1 occurrences)
Last logged: 6:51:08 PM

Error during setup of component webrtc
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
    result = await task
  File "/config/custom_components/webrtc/__init__.py", line 75, in async_setup
    utils.register_static_path(hass.http.app, url_path, path)
  File "/config/custom_components/webrtc/utils.py", line 74, in register_static_path
    app['allow_cors'](route)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 186, in __getitem__
    return self._state[key]
KeyError: 'allow_cors'

I have tried different versions of the plugin all with the same error.

**Comment by AlexxIT** [comment]
#270
