### ISSUE TITLE
Vstarcam C63S not working

### ISSUE THREAD

**Issue by Sygnus83** [AlexxIT/WebRTC#287]
Hi !

I'm using Your great card with D-link Dcs-960L and all working fine.

Now i change to Vstarcam C63S and  now its not working. No error , stopped at the " starting connection (WebRTC)"

The format its:
rtsp://username:pass@192.168.1.133:554/udp/av0_0

I'm test the stream on vlc and its working .

Simply not supporte camera, never will work ?
Thanks for your help !

**Comment by AlexxIT** [comment]
Can you show screen with error?

**Comment by Sygnus83** [comment]
Dont have error, only restart, and black screen.

![HA1](https://user-images.githubusercontent.com/92396929/162624980-9b1376e1-808d-466e-a06c-c54dca1bfb0d.jpg)

**Comment by AlexxIT** [comment]
Have you tried latest version?
https://github.com/AlexxIT/WebRTC/releases/tag/v2.3.0

**Comment by AlexxIT** [comment]
Have you checked demo bunny video?

**Comment by Sygnus83** [comment]
yes, it works, it just stumbles

**Comment by Sygnus83** [comment]
2022-04-11 20:54:25 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:54:25 | 404 | 13.177µs | 127.0.0.1 | GET "/streams"
2022-04-11 20:54:26 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:54:26 | 404 | 148.749µs | 127.0.0.1 | GET "/static/"
2022-04-11 20:54:38 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:54:38 | 404 | 17.239µs | 127.0.0.1 | GET "/streams"
2022-04-11 20:54:38 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:54:38 | 404 | 224.322µs | 127.0.0.1 | GET "/static/"
2022-04-11 20:54:59 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:54:59 | 404 | 19.479µs | 127.0.0.1 | GET "/streams"
2022-04-11 20:54:59 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:54:59 | 404 | 184.322µs | 127.0.0.1 | GET "/static/"
2022-04-11 20:55:39 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:55:39 | 404 | 16.718µs | 127.0.0.1 | GET "/streams"
2022-04-11 20:55:39 DEBUG (webrtc) [custom_components.webrtc.utils] [GIN] 2022/04/11 - 20:55:39 | 404 | 130.364µs | 127.0.0.1 | GET "/static/"
2022-04-11 20:55:40 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/11 20:55:40 Stream Try Connect rtsp://XXXX:XXXXX@192.168.1.133:10554/udp/av0_0
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] panic: runtime error: slice bounds out of range [:-1]
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils]
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] goroutine 69 [running]:
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] github.com/deepch/vdk/format/mp4f.(*Muxer).GetInit(0x40000b89b0, 0x40000a1d50, 0x0, 0x0, 0x0, 0x0, 0x400003cd28, 0x3, 0x0)
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] C:/Users/Alexey/go/pkg/mod/github.com/deepch/vdk@v0.0.0-20210728141153-4453d7a3dc15/format/mp4f/muxer.go:278 +0x814
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] main.startMSE(0x40000fcc60, 0x40000a219c, 0x33)
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] q:/Development/Go/RTSPtoWebRTC/http.go:269 +0x33c
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] created by main.ws
2022-04-11 20:55:41 DEBUG (webrtc) [custom_components.webrtc.utils] 2022/04/11 20:55:41 Server Start Awaiting Signal

**Comment by AlexxIT** [comment]
So duplicate #234
