### ISSUE TITLE
Update to 3.0.2 breaks working installation

### ISSUE THREAD

**Issue by Sjeiz** [AlexxIT/WebRTC#414]
Upgrading to v3.0.2 breaks my working webrtc installation.

_ERROR: NotSupportedIssue: Failed to execute 'addSourceBuffer' on 'MediaSource': The type provided ('video/mp4; codecs="undefined") is unsupported._

Reverting back to v3.0.1 fixes the issue.

Log file:
2023-02-02 22:36:24.201 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/config/custom_components/webrtc/__init__.py", line 204, in get
    await ws_server.prepare(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_ws.py", line 138, in prepare
    payload_writer = await super().prepare(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 421, in prepare
    return await self._start(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 429, in _start
    await self._write_headers()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_response.py", line 502, in _write_headers
    await writer.write_headers(status_line, self._headers)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 131, in write_headers
    self._write(buf)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/http_writer.py", line 76, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

**Comment by AlexxIT** [comment]
Show screen with `NotSupportedIssue`
