### ISSUE TITLE
2023.3 Upgrade - Uncaught thread exception

### ISSUE THREAD

**Issue by ziptbm** [AlexxIT/WebRTC#445]
After upgrading to 2023.3, I'm getting this error in my logs.  Reporting it here, but unclear if I need to do something on my end to fix.

```
This error originated from a custom integration.

Logger: root
Source: custom_components/webrtc/utils.py:235
Integration: WebRTC Camera (documentation, issues)
First occurred: March 1, 2023 at 18:20:53 (1 occurrences)
Last logged: March 1, 2023 at 18:20:53

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/config/custom_components/webrtc/utils.py", line 235, in run
    self.process = subprocess.Popen(
  File "/usr/local/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.10/subprocess.py", line 1847, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/config/go2rtc-1.2.0'
```

**Comment by AlexxIT** [comment]
Try to delete file `/config/go2rtc-1.2.0`, so integration redownload it. Maybe there was some problem with internet.

**Comment by ziptbm** [comment]
> Try to delete file `/config/go2rtc-1.2.0`, so integration redownload it. Maybe there was some problem with internet.

This issue only appeared after the upgrade, so I'll close this out.  Thanks for the response and guidance.
