### ISSUE TITLE
Home Assistant media_player not working

### ISSUE THREAD

**Issue by ondoteam** [AlexxIT/WebRTC#471]
Hello. I am trying to add a Dahua camera as media_player in Home Assistant. The camera is actually working as a two-way communication device using go2rtc without problems.

```
"medias": [
        "video, recvonly, H.264 Main 5.0",
        "audio, recvonly, PCMA/8000",
        "audio, sendonly, L16/8000, L16/16000, PCMA/8000, PCMA/16000, PCMU/8000, PCMU/16000, G726-40/8000, G726-40/16000, MPEG4-GENERIC/8000, MPEG4-GENERIC/16000",
        "application, recvonly, VND.ONVIF.METADATA"
      ],
```

I am adding the following code to media_player.yaml in Home Assistant

```
- platform: webrtc
  name: Dahua Camera
  stream: dahua_camera
  audio: pcmu/8000
```

The **stream: dahua_camera** is the name for the stream in go2rtc (I am using the binary file for Windows and not the HA addon).

```
streams:
  dahua_camera:
    - rtsp://admin:[...]
```

After a Home Assistant restart, I can see the new media_player entity, but there is no way to send audio (for example a Google TTS). It always show and error like "Unable to find sevice media_player/play_media."

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1820, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1857, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 216, in handle_service
await service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 798, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 977, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 838, in _handle_entity_call
await result
File "/config/custom_components/webrtc/media_player.py", line 74, in async_play_media
assert r.ok
AssertionError
```

I can send TTS using Google to any media device that I have configured.

**Comment by AlexxIT** [comment]
`audio:` is tempalte name from FFmpeg source. There is no `pcmu/8000` template. It's called just `pcmu`:
https://github.com/AlexxIT/go2rtc#source-ffmpeg

But I recommend you to use `aac/16000` or `pcm/16000`. It have better quality. Your camera support them.

PS. You can use `pcm/16000` only for go2rtc v1.3+

**Comment by ondoteam** [comment]
> 

Still getting same error using pcm/16000

**Comment by AlexxIT** [comment]
Try to play audio from go2rtc WebUI

**Comment by ondoteam** [comment]
Hello! I was copying the logs for you and I saw an error from ffmpeg. I have updated the binary on Windows and it is working now. Thank you and sorry for wasting your time

```
Version: 2023-04-12-git-1179bb703e-full_build-www.gyan.dev
```
