### ISSUE TITLE
HA Cant stream Picam

### ISSUE THREAD

**Issue by bibitocarlos** [AlexxIT/WebRTC#510]
Hi,
I use Webrtc to stream my picam V2 to homeassistant.
I have installed the latest version, but get this error, any idea ? : 

```
Logger: homeassistant.helpers.integration_platform
Source: loader.py:850
First occurred: 11:28:14 (6 occurrences)
Last logged: 17:40:36

    Unexpected error importing webrtc/recorder.py
    Unexpected error importing webrtc/logbook.py
    Unexpected error importing webrtc/system_health.py
    Unexpected error importing webrtc/media_source.py
    Unexpected error importing webrtc/hardware.py

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/integration_platform.py", line 50, in _async_process_single_integration_platform_component
    platform = integration.get_platform(platform_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 833, in get_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 850, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'custom_components.WebRTC.diagnostics'

```

**Comment by AlexxIT** [comment]
This files not from this integration:
```
    Unexpected error importing webrtc/recorder.py
    Unexpected error importing webrtc/logbook.py
    Unexpected error importing webrtc/system_health.py
    Unexpected error importing webrtc/media_source.py
    Unexpected error importing webrtc/hardware.py
```
