### ISSUE TITLE
Black screen on computer browser

### ISSUE THREAD

**Issue by pszafer** [AlexxIT/WebRTC#559]
Hi,

First, thanks for this integration!
It's working on my mobile phone, but it's not working on regular browser (same wifi), only black screen with RTP
I checked different browser, tried to debug as much as I can.

Debug logs:

```
2023-08-30 08:13:16.162 ERROR (MainThread) [homeassistant] Error doing job: Fatal read error on STARTTLS transport
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioopenssl/__init__.py", line 493, in _read_ready
    data = self._sock.recv(self.MAX_SIZE)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/OpenSSL/SSL.py", line 2056, in recv
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.11/site-packages/OpenSSL/SSL.py", line 1794, in _raise_ssl_error
    raise ZeroReturnError()
OpenSSL.SSL.ZeroReturnError
2023-08-30 08:13:38.001 DEBUG (MainThread) [custom_components.webrtc] New client: {'authSig': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzNmNhMDljZmE1YjM0NDEwYjg1YWY5NmRjYTRlNzdkZCIsInBhdGgiOiIvYXBpL3dlYnJ0Yy93cyIsInBhcmFtcyI6W10sImlhdCI6MTY5MzM3NjAxNywiZXhwIjoxNjkzMzc2MDQ3fQ.aWCS6PVE8HIdSq5MA9Gmj7QB6qmZTYIc2vOo4K5seIw', 'url': 'rtsp://192.168.51.45/ch0_0.h264'}
```

I don't know if `OpenSSL.SSL.ZeroReturnError` comes from this integration.
Camera is on different vlan, just fyi.

Any thoughts?

**Comment by pszafer** [comment]
camera resetted itself and switched to H.265. Sorry for bothering
