### ISSUE TITLE
Camera Cast Problem

### ISSUE THREAD

**Issue by Richie-Kotzen** [AlexxIT/WebRTC#667]
Good morning everyone, I found this project very useful for sending the real-time video stream from one of my cameras to Chromecast. When I try to send a video however nothing happens and reading the logs I found this error. What can it be?
```
Can't DashCast to ['media_player.tv_cameretta']
Traceback (most recent call last):
  File "/config/custom_components/webrtc/utils.py", line 191, in dash_cast
    entity.dashcast.load_url(url, force = force)
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/dashcast.py", line 71, in load_url
    self.launch(
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/__init__.py", line 97, in launch
    self._socket_client.receiver_controller.launch_app(
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/receiver.py", line 174, in launch_app
    self._send_launch_message(app_id, force_launch, callback_function)
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/receiver.py", line 229, in _send_launch_message
    callback_function(True, None)
  File "/usr/local/lib/python3.12/site-packages/pychromecast/response_handler.py", line 67, in _callback
    on_success(callback_function=callback_function)
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/dashcast.py", line 67, in launch_callback
    self.send_message(
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/__init__.py", line 148, in send_message
    self.launch(
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/__init__.py", line 97, in launch
    self._socket_client.receiver_controller.launch_app(
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/receiver.py", line 174, in launch_app
    self._send_launch_message(app_id, force_launch, callback_function)
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/receiver.py", line 229, in _send_launch_message
    callback_function(True, None)
  File "/usr/local/lib/python3.12/site-packages/pychromecast/response_handler.py", line 67, in _callback
    on_success(callback_function=callback_function)
  File "/usr/local/lib/python3.12/site-packages/pychromecast/controllers/__init__.py", line 186, in send_message_nocheck
    self._message_func(
  File "/usr/local/lib/python3.12/site-packages/pychromecast/socket_client.py", line 949, in send_app_message
    raise UnsupportedNamespace(
pychromecast.error.UnsupportedNamespace: Namespace urn:x-cast:com.madmod.dashcast is not supported by current app. Supported are urn:x-cast:com.google.cast.debugoverlay, urn:x-cast:com.google.cast.cac, urn:x-cast:com.google.cast.sse, urn:x-cast:com.google.cast.remotecontrol
```
Thank you all

**Comment by stahelp** [comment]
Same issue here. I have just deleted and reinstalled HACS and integration, no luck.
WebRTC Version 3.5.1
HA Core 2024.3.0
Supervisor 2024.03.0
OS 12.1
Frontend 20240306.0

Not sure when the issue started
Thank you for any help.

**Comment by stahelp** [comment]
Closed issue 664 shows the solution. Worked for me as well.

Thank you

**Comment by AlexxIT** [comment]
Looks like your Chromecast device doesn't support DashCast app. Can't do anything about this.
